# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.102.0"

default_platform :ios

platform :ios do
  desc "Build .ipa and dSYM"
  lane :build do
    gym(scheme: "Tenfold", use_legacy_build_api: true)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    deliver(force: true, skip_metadata: true, skip_screenshots: true)
  end
end
